"""init

Revision ID: 07a2aa0281eb
Revises: 
Create Date: 2025-10-03 17:22:48.459544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a2aa0281eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedBy', sa.String(length=50), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=50), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('todo_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('CreatedBy', sa.String(length=50), nullable=True),
    sa.Column('UpdatedBy', sa.String(length=50), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('todo')
    # ### end Alembic commands ###
